# Generated by Django 6.0.3 on 2026-04-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ('id',)},
        ),
    ]
