# Generated by Django 6.0.3 on 2026-05-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
